// Canonical brand groups for the « Marques » filter + self-hosted favicons
// (public/brand-icons/, regenerated by npm run build:icons).
//
// The OSM index carries ~1000 distinct labels: spelling variants of the same
// enseigne ("Total" / "TotalEnergies" / "Total Contact", "E.Leclerc" /
// "E. Leclerc", "Esso" / "Esso Express"…) plus a long tail of one-off
// independent stations. Listing them raw makes the filter unusable, so each
// label resolves to ONE group below — first match wins — and everything
// unrecognized falls into « Indépendants & autres ». Patterns match both a
// bare brand ("TotalEnergies") and a full display name
// ("Total Access · Tournefeuille"), so favorites — which only persist the
// name — resolve too.

/** Every banner of the U cooperative — one enseigne, one card program */
const U_FAMILY = /super\s?u|hyper\s?u|système u|u express|station\s?u|enseignes u|^u\s*(·|$)/i;

/** Filter group for unrecognized brands and stations without brand data */
export const INDEPENDENT_GROUP = 'Indépendants & autres';

interface BrandGroupDef {
  label: string;
  match: RegExp;
  /** public/brand-icons/<icon>.png — absent when we have no usable logo */
  icon?: string;
}

// Total Access stays distinct from TotalEnergies (discount banner, prices
// differently); the other Total variants are label noise and merge.
const BRAND_GROUPS: ReadonlyArray<BrandGroupDef> = [
  { label: 'Total Access', match: /total\s*access/i, icon: 'total' },
  { label: 'TotalEnergies', match: /total|elf\b/i, icon: 'total' },
  { label: 'Intermarché', match: /intermarch|mousquetaires/i, icon: 'intermarche' },
  { label: 'Carrefour', match: /carrefour/i, icon: 'carrefour' },
  { label: 'E.Leclerc', match: /leclerc/i, icon: 'leclerc' },
  { label: 'Enseignes U', match: U_FAMILY, icon: 'u' },
  { label: 'Auchan', match: /auchan/i, icon: 'auchan' },
  { label: 'Avia', match: /avia/i, icon: 'avia' },
  { label: 'Esso', match: /esso/i, icon: 'esso' },
  { label: 'Shell', match: /shell/i, icon: 'shell' },
  { label: 'BP', match: /\bbp\b/i },
  { label: 'Eni / Agip', match: /\beni\b|agip/i, icon: 'eni' },
  { label: 'Casino', match: /casino|g[ée]ant/i },
  { label: 'Cora', match: /cora\b/i },
  { label: 'Netto', match: /netto/i, icon: 'netto' },
  { label: 'Lidl', match: /lidl/i, icon: 'lidl' },
  { label: 'Aldi', match: /aldi/i, icon: 'aldi' },
  { label: 'Spar', match: /spar\b/i, icon: 'spar' },
  { label: 'Colruyt', match: /colruyt/i, icon: 'colruyt' },
  { label: 'Dyneff', match: /dyneff/i, icon: 'dyneff' },
  { label: 'AS 24', match: /as\s?24/i, icon: 'as24' },
  { label: 'Tamoil', match: /tamoil/i, icon: 'tamoil' },
  { label: 'Élan', match: /^[ée]lan\b/i },
  { label: 'Vito', match: /^vito\b/i },
];

/** Every filter entry the app knows — drives the « hors zone » selector. */
export const KNOWN_BRAND_GROUPS: readonly string[] = [
  ...BRAND_GROUPS.map((g) => g.label),
  INDEPENDENT_GROUP,
];

/**
 * Grouping key for the brand filter. A station without brand data counts as
 * independent — its enseigne is unknown to every source, which in practice
 * means it isn't part of a national network.
 */
export function brandGroup(brand: string | undefined): string {
  if (!brand) return INDEPENDENT_GROUP;
  for (const g of BRAND_GROUPS) if (g.match.test(brand)) return g.label;
  return INDEPENDENT_GROUP;
}

/** Icon URL for a brand or display name, or null when we have no logo. */
export function brandIconSrc(label: string | undefined): string | null {
  if (!label) return null;
  for (const g of BRAND_GROUPS) {
    if (g.match.test(label)) return g.icon ? `/brand-icons/${g.icon}.png` : null;
  }
  return null;
}
