import { test, expect, gotoMap } from './fixtures'

// The gouv flux has no station names: brands come from the static OpenStreetMap
// index (/brands-fr.json, generated by scripts/build-brand-index.mjs) matched
// by proximity. A station within 150 m of an indexed POI must wear its brand.

test.use({ seed: { sourceId: 'gouv', onboarded: true } })

test('stations take their brand from the static index', async ({ page }) => {
  // Deterministic gouv flux: one station at the queried center.
  await page.route('**/proxy/gouv/**', async (route) => {
    const where = new URL(route.request().url()).searchParams.get('where') ?? ''
    const m = /POINT\(([-\d.]+) ([-\d.]+)\)/.exec(where)
    const lng = m ? parseFloat(m[1]) : 1.4442
    const lat = m ? parseFloat(m[2]) : 43.6047
    await route.fulfill({
      json: {
        total_count: 1,
        results: [
          {
            id: 'e2e-brand-1',
            ville: 'Testville',
            adresse: '1 rue du Test',
            geom: { lat, lon: lng },
            gazole_prix: '1.80',
            e10_prix: '1.70',
          },
        ],
      },
    })
  })

  // Deterministic index: one labeled POI ~30 m from the default position
  // (Toulouse Capitole), where the station above lands.
  await page.route('**/brands-fr.json', (route) =>
    route.fulfill({ json: { v: 1, labels: ['Super U'], pois: [[43.6050, 1.4442, 0]] } }),
  )

  await gotoMap(page)
  await expect(page.getByText('Super U · Testville').first()).toBeVisible()
})
