import { test, expect, gotoMap } from './fixtures'

// The gouv flux has no station names: brands come from the static OpenStreetMap
// index (/brands-fr.json, generated by scripts/build-brand-index.mjs) matched
// by proximity. A station within 150 m of an indexed POI must wear its brand.

test.use({ seed: { sourceId: 'gouv', onboarded: true } })

test('stations take their brand from the static index', async ({ page }) => {
  // Deterministic gouv flux: two stations near the queried center.
  await page.route('**/proxy/gouv/**', async (route) => {
    const where = new URL(route.request().url()).searchParams.get('where') ?? ''
    const m = /POINT\(([-\d.]+) ([-\d.]+)\)/.exec(where)
    const lng = m ? parseFloat(m[1]) : 1.4442
    const lat = m ? parseFloat(m[2]) : 43.6047
    const station = (i: number, dLat: number) => ({
      id: `e2e-brand-${i}`,
      ville: 'Testville',
      adresse: `${i} rue du Test`,
      geom: { lat: lat + dLat, lon: lng },
      gazole_prix: `1.8${i}`,
      e10_prix: `1.7${i}`,
    })
    await route.fulfill({
      json: { total_count: 2, results: [station(1, 0), station(2, 0.01)] },
    })
  })

  // Deterministic index: two U-banner POIs ~30 m from each station, at the
  // default position (Toulouse Capitole) where the stations above land.
  await page.route('**/brands-fr.json', (route) =>
    route.fulfill({
      json: {
        v: 1,
        labels: ['Super U', 'U Express'],
        pois: [
          [43.605, 1.4442, 0],
          [43.6149, 1.4442, 1],
        ],
      },
    }),
  )

  await gotoMap(page)
  await expect(page.getByText('Super U · Testville').first()).toBeVisible()

  // The brand list is collapsed behind an accordion — expand it first.
  await page.getByText(/^Filtres · \d+$/).click()
  await page.getByRole('button', { name: /^Marques/ }).click()

  // Both U banners group as one « Enseignes U » filter entry…
  const uRow = page.getByRole('button', { name: /Enseignes U/ })
  await expect(uRow).toContainText('2')
  // …and selecting it keeps both stations
  await uRow.click()
  await expect(page.getByText('Voir 2 stations')).toBeVisible()

  // A brand absent from the zone is still selectable (« hors de la zone »),
  // and adding it to the selection never hides matching stations.
  await page.getByRole('button', { name: 'Shell', exact: true }).click()
  await expect(page.getByText('Voir 2 stations')).toBeVisible()
})
